title: Data Science in Chemical Engineering
author: Maya Fetzer & Dr. Jude Okolie — Bucknell University
copyright: "2024"

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  home_page_in_navbar: true

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - tasklist
  myst_heading_anchors: 3

repository:
  url: https://github.com/AlnurGazizuly/data-science-in-cheme
  branch: main

launch_buttons:
  jupyterhub_url: ""
  thebe: false

sphinx:
  extra_extensions:
    - sphinx_copybutton
    - jupyterlite_sphinx
  config:
    html_show_sourcelink: false
    pygments_dark_style: monokai
    jupyterlite_sphinx_strip_tagged_cells: true
    html_theme_options:
      default_mode: dark
      show_navbar_depth: 2
      navigation_with_keys: true
      repository_url: "https://github.com/AlnurGazizuly/data-science-in-cheme"
      use_fullscreen_button: true
      toc_title: "On this page"
      logo:
        text: "DS in ChemE"
